float x = 0.5;

size(1200,1200);
background(255);
smooth();

line(x,0,x,height);
x = x * 1.2;
line(x,0,x,height);
x = x * 1.2;
line(x,0,x,height);
x = x * 1.2;
line(x,0,x,height);
x = x * 1.2;
line(x,0,x,height);
x = x * 1.2;
line(x,0,x,height);
x = x * 1.2;
line(x,0,x,height);
x = x * 1.2;
line(x,0,x,height);
x = x * 1.2;
line(x,0,x,height);
x = x * 1.2;
line(x,0,x,height);
x = x * 1.2;
line(x,0,x,height);
x = x * 1.2;
line(x,0,x,height);
x = x * 1.2;
line(x,0,x,height);
x = x * 1.2;
line(x,0,x,height);
x = x * 1.2;
line(x,0,x,height);
x = x * 1.2;
line(x,0,x,height);
x = x * 1.2;
line(x,0,x,height);
x = x * 1.2;
line(x,0,x,height);
x = x * 1.2;
line(x,0,x,height);
x = x * 1.2;
line(x,0,x,height);
x = x * 1.2;
line(x,0,x,height);
x = x * 1.2;
line(x,0,x,height);
x = x * 1.2;
line(x,0,x,height);
x = x * 1.2;
line(x,0,x,height);
x = x * 1.2;
line(x,0,x,height);
x = x * 1.2;
line(x,0,x,height);
x = x * 1.2;
line(x,0,x,height);
x = x * 1.2;
line(x,0,x,height);
x = x * 1.2;
line(x,0,x,height);
x = x * 1.2;
line(x,0,x,height);
x = x * 1.2;
line(x,0,x,height);
x = x * 1.2;
line(x,0,x,height);
x = x * 1.2;
line(x,0,x,height);
x = x * 1.2;
line(x,0,x,height);
x = x * 1.2;
line(x,0,x,height);
x = x * 1.2;
line(x,0,x,height);
x = x * 1.2;
line(x,0,x,height);
x = x * 1.2;
line(x,0,x,height);
x = x * 1.2;
line(x,0,x,height);
x = x * 1.2;
line(x,0,x,height);
x = x * 1.2;
line(x,0,x,height);
x = x * 1.2;
line(x,0,x,height);
x = x * 1.2;
line(x,0,x,height);
x = x * 1.2;
line(x,0,x,height);
x = x * 1.2;
line(x,0,x,height);
x = x * 1.2;
line(x,0,x,height);
x = x * 1.2;
line(x,0,x,height);
x = x * 1.2;
line(x,0,x,height);
x = x * 1.2;
